services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
        - NEXT_PUBLIC_WHATSAPP=${NEXT_PUBLIC_WHATSAPP}
        - NEXT_PUBLIC_CONTACT_EMAIL=${NEXT_PUBLIC_CONTACT_EMAIL}
        - NEXT_PUBLIC_PHONE=${NEXT_PUBLIC_PHONE}
    container_name: hayexperiencia-web
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      coolify:
        aliases:
          - hayexperiencia-web
    volumes:
      - /data/coolify/applications/hhc1afp29any1kulfucplz13/media:/app/media
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-hhc1afp29any1kulfucplz13.entryPoints=http
      - traefik.http.routers.http-0-hhc1afp29any1kulfucplz13.middlewares=redirect-to-https
      - "traefik.http.routers.http-0-hhc1afp29any1kulfucplz13.rule=Host(`hayexperiencia.com`) && PathPrefix(`/`)"
      - traefik.http.routers.http-0-hhc1afp29any1kulfucplz13.service=http-0-hhc1afp29any1kulfucplz13
      - traefik.http.routers.http-1-hhc1afp29any1kulfucplz13.entryPoints=http
      - traefik.http.routers.http-1-hhc1afp29any1kulfucplz13.middlewares=redirect-to-https
      - "traefik.http.routers.http-1-hhc1afp29any1kulfucplz13.rule=Host(`www.hayexperiencia.com`) && PathPrefix(`/`)"
      - traefik.http.routers.http-1-hhc1afp29any1kulfucplz13.service=http-1-hhc1afp29any1kulfucplz13
      - traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.entryPoints=https
      - traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.middlewares=gzip
      - "traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.rule=Host(`hayexperiencia.com`) && PathPrefix(`/`)"
      - traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.service=https-0-hhc1afp29any1kulfucplz13
      - traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-hhc1afp29any1kulfucplz13.tls=true
      - traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.entryPoints=https
      - traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.middlewares=gzip
      - "traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.rule=Host(`www.hayexperiencia.com`) && PathPrefix(`/`)"
      - traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.service=https-1-hhc1afp29any1kulfucplz13
      - traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.tls.certresolver=letsencrypt
      - traefik.http.routers.https-1-hhc1afp29any1kulfucplz13.tls=true
      - traefik.http.services.http-0-hhc1afp29any1kulfucplz13.loadbalancer.server.port=3000
      - traefik.http.services.http-1-hhc1afp29any1kulfucplz13.loadbalancer.server.port=3000
      - traefik.http.services.https-0-hhc1afp29any1kulfucplz13.loadbalancer.server.port=3000
      - traefik.http.services.https-1-hhc1afp29any1kulfucplz13.loadbalancer.server.port=3000

networks:
  coolify:
    external: true
    name: coolify
